# Project: Project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = configuration.o main.o produto.o
LINKOBJ  = configuration.o main.o produto.o
LIBS     = -L"E:/PortableApps/Dev-Cpp/MinGW64/lib" -L"E:/PortableApps/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/PortableApps/Dev-Cpp/MinGW64/include" -I"E:/PortableApps/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/PortableApps/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/PortableApps/Dev-Cpp/MinGW64/include" -I"E:/PortableApps/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/PortableApps/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/PortableApps/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

configuration.o: configuration.c
	$(CC) -c configuration.c -o configuration.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

produto.o: produto.c
	$(CC) -c produto.c -o produto.o $(CFLAGS)
